apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alloy.alloy.configMap.name }}
data:
  config: |
    logging {
      level = "{{ .Values.alloy.config.logging.level }}"
    }
    discovery.kubernetes "pods" {
      role = "pod"
      {{- if .Values.alloy.config.selector.label.enabled }}
      selectors {
        role = "pod"
        label = "{{ .Values.alloy.config.selector.label.label }}"
      }
      {{- end }}
      {{- if .Values.alloy.config.selector.namespace.enabled }}
      namespaces {
        names = [
          {{- range $key, $value := .Values.alloy.config.selector.namespace.namespaces }}
          "{{ $value }}",
          {{- end }}
        ]
      }
      {{- end }}
    }
    discovery.relabel "default" {
      targets = discovery.kubernetes.pods.targets
      rule {
        action        = "replace"
        source_labels = ["__meta_kubernetes_namespace"]
        target_label  = "namespace"
      }
      rule {
        action        = "replace"
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label  = "pod"
      }
      rule {
        action        = "replace"
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label  = "container"
      }
      rule {
        action        = "replace"
        source_labels = ["__meta_kubernetes_pod_node_name"]
        target_label  = "node"
      }
      rule {
        action        = "replace"
        source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
        target_label  = "service_name"
        regex         = "(.+)"
      }
      rule {
        action        = "replace"
        source_labels = ["__meta_kubernetes_pod_label_opentelemetry_io_name"]
        target_label  = "service_name"
        regex         = "(.+)"
      }
    }
    loki.source.kubernetes "pods" {
      targets    = discovery.relabel.default.output
      forward_to = [loki.process.pods.receiver]
    }
    loki.process "pods" {
      stage.label_keep {
        values = ["namespace","pod","container","service_name"]
      }
      forward_to = [loki.write.default.receiver]
    }
    loki.write "default" {
      endpoint {
        url = "{{ .Values.alloy.config.endpoint.url }}"
        {{- if .Values.alloy.config.endpoint.tls.enabled }}
        tls_config {
          insecure_skip_verify = {{ .Values.alloy.config.endpoint.tls.skip_verify }}
        }
        {{- end }}
      }
      external_labels = {
        {{- range $key, $value := .Values.alloy.config.labels }}
        {{ $key }} = "{{ $value }}",
        {{- end }}
      }
    }
