apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "hermes.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config.data | toYaml | indent 4 }}
