name: istio-gateway
gatewayClassName: istio
addresses: []
  # - type: IPAddress
  #   value: 10.1.1.5

service:
  annotations: {}
  spec: {}
    # type: LoadBalancer
    # externalTrafficPolicy: Local
    # healthCheckNodePort: 30042

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: istio-gateway
          operator: In
          values:
          - "true"

listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: All
    # tls:
    #   mode: Terminate
    #   certificateRefs:
    #   - kind: Secret
    #     group: cert-manager.io
    #     name: wildcard-example-infra-cloud

certificates: []
  # - name: wildcard-example-infra-cloud
  #   issuer:
  #     kind: ClusterIssuer
  #     name: selfsigned-cluster-issuer
  #   hosts:
  #     - "*.example.infra.cloud"
