apiVersion: v2
name: lamp-victoria-metrics
version: 1.2.0

annotations:
  notes: "VictoriaMetrics v1.131.0, configurable RBAC roles for VMAgent."

dependencies:
  - name: prometheus-operator-crds
    version: 23.0.0
    repository: https://prometheus-community.github.io/helm-charts

  - name: victoria-metrics-k8s-stack
    version: 0.72.4
    repository: https://victoriametrics.github.io/helm-charts/