{{- range .Values.certificates }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
spec:
  secretName: {{ .name }}
  issuerRef:
    group: {{ .issuer.group }}
    name: {{ .issuer.name }}
    kind: {{ .issuer.kind }}
  dnsNames:
  {{- range .hosts }}
    - {{ . | quote }}
  {{- end }}
{{- end }}
