apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.name }}
spec:
  {{- with .Values.addresses }}
  addresses:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  gatewayClassName: {{ .Values.gatewayClassName }}
  {{- with .Values.listeners }}
  listeners:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: {{ .Values.name }}-config
