{{- if .Values.mcp.oracle.enabled }}
{{- range $item := .Values.mcp.oracle.mcps }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $item.name }}-mcp-secret
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.externalSecrets.kind }}
    name: {{ $.Values.externalSecrets.name }}
  target:
    name: {{ $item.name }}-mcp-secret
    creationPolicy: {{ $.Values.externalSecrets.creationPolicy }}
  data:
    - secretKey: config
      remoteRef:
        key: {{ $item.config.key }}
        {{- with $item.config.property }}
        property: {{ . }}
        {{- end }}
    {{- range $item.keyFiles }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ $item.config.key }}
        property: {{ .property }}
    {{- end }}
{{- end }}
{{- end }}
