apiVersion: v2
name: lamp-cert-manager
version: 0.2.1

dependencies:
  - name: cert-manager
    version: v1.20.1
    repository: https://charts.jetstack.io

  - name: origin-ca-issuer
    version: 0.6.2
    repository: oci://ghcr.io/cloudflare/origin-ca-issuer-charts
    condition: issuers.originCAIssuer.enabled

annotations:
  notes: "Fixes in ACME HTTP-01, IPv6 support in policies, Go update."
