cert-manager:
  installCRDs: true
  extraArgs: # Avoid to use internal DNS server
    - --dns01-recursive-nameservers-only
    - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53 
  prometheus:
    servicemonitor:
      enabled: false
  serviceAccount:
    create: true
    name: cert-manager
  webhook:
    validatingWebhookConfigurationAnnotations:
      admissions.enforcer/disabled: "true"

issuers:
  selfsigned: true
  letsencrypt:
    http: false
    cloudflare: 
      enabled: false
      remoteSecretKey: cloudflare-dns-solver-token 
  zerossl:
    enabled: false
    keyID: #from zerossl web site
    remoteSecretKeys:
      zerossl: zerossl-api-token
      cloudflare: cloudflare-dns-solver-token
  originCAIssuer:
    enabled: false
    tokenRemoteSecretKey: origin-ca-issuer-token

origin-ca-issuer:
  controller:
    resources:
      requests:
        cpu: "10m"
        memory: 10Mi
      limits:
        cpu: "1"
        memory: 512Mi
        
externalSecrets:
  kind: ClusterSecretStore
  name: oracle
  refreshInterval: 1h
  creationPolicy: Orphan
