
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
spec:
  refreshInterval: "{{ .Values.externalSecrets.refreshInterval }}"
  secretStoreRef:
    kind: "{{ .Values.externalSecrets.kind }}"
    name: "{{ .Values.externalSecrets.name }}"
  target:
    name: operator-oauth
    creationPolicy: "{{ .Values.externalSecrets.creationPolicy }}"
    template:
      data:
        client_id: "{{`{{ .oauth_client_id }}`}}"
        client_secret: "{{`{{ .oauth_client_secret }}`}}"
  dataFrom:
  - extract:
      key: "{{ .Values.remoteSecretKeys.tailscale }}"
