apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
spec:
  refreshInterval: "{{ .Values.externalSecrets.refreshInterval }}"
  secretStoreRef:
    kind: "{{ .Values.externalSecrets.kind }}"
    name: "{{ .Values.externalSecrets.name }}"
  target:
    name: cloudflare
    creationPolicy: "{{ .Values.externalSecrets.creationPolicy }}"
    template:
      data:
        token: "{{`{{ .value }}`}}"
  data:
  - secretKey: value
    remoteRef:
      key: "{{ .Values.cloudflare.remoteSecretKey }}"
