apiVersion: v2
name: lamp-remnawave-panel
version: 1.1.0

annotations:
  notes: "Initial version and basic configuration."

dependencies:
  - name: valkey
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: 5.4.11
    condition: valkey.enabled
  - name: postgresql
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: 18.6.2
    condition: postgresql.enabled
