{{- if .Values.cluster.backups.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster.backups.secret.name }}
spec:
  refreshInterval: "{{ .Values.externalSecrets.refreshInterval }}"
  secretStoreRef:
    kind: "{{ .Values.externalSecrets.kind }}"
    name: "{{ .Values.externalSecrets.name }}"
  target:
    name: {{ .Values.cluster.backups.secret.name }}
    creationPolicy: "{{ .Values.externalSecrets.creationPolicy }}"
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: "{{ .Values.backupCredentials.remoteSecretKey }}"
        property: "{{ .Values.backupCredentials.accessKeyProperty }}"
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: "{{ .Values.backupCredentials.remoteSecretKey }}"
        property: "{{ .Values.backupCredentials.secretKeyProperty }}"
{{- end }}
