{{- range .Values.image.pullSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ include "app.fullname" $ }}-image-pull-secret-{{ .name }}"
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.externalSecrets.kind }}
    name: {{ $.Values.externalSecrets.name }}
  target:
    name: "{{ include "app.fullname" $ }}-image-pull-secret-{{ .name }}"
    creationPolicy: "{{ $.Values.externalSecrets.creationPolicy }}"
    template:
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "-1"
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .url }}": {
                "auth": "{{`{{ printf "%s:%s" "`}}{{ .username }}{{`" .password | b64enc }}`}}"
              }
            }
          }
  data:
    - secretKey: password
      remoteRef:
        key: {{ .passwordRemoteSecretKey }}
{{- end }}
