cloudflare:
  remoteSecretKey: cloudflare-dns-solver-token

external-dns:
  # domainFilters:
  #   - from-the-lamp.work
  extraArgs:
    - --cloudflare-proxied
  sources:
    - service
  policy: sync
  logLevel: debug
  provider: 
    name: cloudflare
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare
          key: token

externalSecrets:
  kind: ClusterSecretStore
  name: oracle
  refreshInterval: 1h
  creationPolicy: Orphan
