{{- if .Values.mcp.argocd.enabled }}
{{- range $item := .Values.mcp.argocd.mcps }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $item.name }}-mcp-secret
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.externalSecrets.kind }}
    name: {{ $.Values.externalSecrets.name }}
  target:
    name: {{ $item.name }}-mcp-secret
    creationPolicy: {{ $.Values.externalSecrets.creationPolicy }}
  data:
    - secretKey: token
      remoteRef:
        key: {{ $item.token.key }}
        property: {{ $item.token.property }}
{{- end }}
{{- end }}
