{{- if .Values.mcp.argocd.enabled }}
{{- range $item := .Values.mcp.argocd.mcps }}
---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: {{ $item.name }}
spec:
  image: {{ $.Values.mcp.argocd.image }}
  transport: stdio
  args:
    - stdio
  groupRef:
    name: {{ $item.groupRef | default $.Values.mcp.defaults.groupRef }}
  permissionProfile:
    type: builtin
    name: {{ $.Values.mcp.defaults.permissionProfile }}
  audit:
    enabled: true
  {{- with $item.toolConfig }}
  toolConfigRef:
    name: {{ $item.name }}-tool-config
  {{- end }}
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          env:
            - name: ARGOCD_BASE_URL
              value: {{ $item.url }}
            - name: ARGOCD_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $item.name }}-mcp-secret
                  key: token
            {{- if $item.readOnly }}
            - name: MCP_READ_ONLY
              value: "true"
            {{- end }}
  {{- with $item.env }}
  env:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $item.toolConfig }}
---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPToolConfig
metadata:
  name: {{ $item.name }}-tool-config
spec:
  {{- with .toolsFilter }}
  toolsFilter:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .toolsOverride }}
  toolsOverride:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
