{{- if .Values.notifications.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
spec:
  refreshInterval: "{{ .Values.externalSecrets.refreshInterval }}"
  secretStoreRef:
    kind: "{{ .Values.externalSecrets.kind }}"
    name: "{{ .Values.externalSecrets.name }}"
  target:
    name: argocd-notifications-secret
    creationPolicy: "{{ .Values.externalSecrets.creationPolicy }}"
    template:
      data:
        slack-token: "{{`{{ .token }}`}}"
  data:
  - secretKey: token
    remoteRef:
      key: {{ .Values.notifications.remoteSecretKeys.slackToken }}
      conversionStrategy: Default	
      decodingStrategy: None	
      metadataPolicy: None
{{- end }}
