{{- if .Values.dex.enabled }}
{{- $connectors := list }}
{{- with .Values.dex.sso.google }}
{{- if .enabled }}
{{- $connectors = append $connectors (dict
      "type" "google"
      "id" "google"
      "name" "Google"
      "config" (dict
        "clientID" "$GOOGLE_CLIENT_ID"
        "clientSecret" "$GOOGLE_CLIENT_SECRET"
        "redirectURI" .redirectURI
        "hostedDomains" .hostedDomains
        "serviceAccountFilePath" "/etc/dex/google/key.json"
        "domainToAdminEmail" .domainToAdminEmail
        "fetchTransitiveGroupMembership" .fetchTransitiveGroupMembership
      )
    )
}}
{{- end }}
{{- end }}
{{- with .Values.dex.sso.zitadel }}
{{- if .enabled }}
{{- $connectors = append $connectors (dict
      "type" "oidc"
      "id" "zitadel"
      "name" "Zitadel"
      "config" (dict
        "issuer" .issuer
        "clientID" "$ZITADEL_CLIENT_ID"
        "clientSecret" "$ZITADEL_CLIENT_SECRET"
        "redirectURI" .redirectURI
      )
    )
}}
{{- end }}
{{- end }}
{{- with .Values.dex.sso.gitlab }}
{{- if .enabled }}
{{- $connectors = append $connectors (dict
      "type" "gitlab"
      "id" "gitlab"
      "name" "GitLab"
      "config" (dict
        "baseURL" .baseURL
        "clientID" "$GITLAB_CLIENT_ID"
        "clientSecret" "$GITLAB_CLIENT_SECRET"
        "redirectURI" .redirectURI
        "groups" .groups
      )
    )
}}
{{- end }}
{{- end }}
{{- $config := mergeOverwrite (dict) .Values.dex.config (dict "connectors" $connectors) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dex.configSecret.name }}
type: Opaque
data:
  config.yaml: {{ toYaml $config | b64enc }}
{{- end }}
