{{- if .Values.dex.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-sso-secrets
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.externalSecrets.kind }}
    name: {{ $.Values.externalSecrets.name }}
  target:
    name: dex-sso-secrets
    creationPolicy: {{ $.Values.externalSecrets.creationPolicy }}
  data:
    {{- with .Values.dex.vmcpClientSecret }}
    - secretKey: VMCP_CLIENT_SECRET
      remoteRef:
        key: {{ .key }}
        {{- with .property }}
        property: {{ . }}
        {{- end }}
    {{- end }}
    {{- with .Values.dex.sso.google }}
    {{- if .enabled }}
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: {{ .clientId.key }}
        {{- with .clientId.property }}
        property: {{ . }}
        {{- end }}
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: {{ .clientSecret.key }}
        {{- with .clientSecret.property }}
        property: {{ . }}
        {{- end }}
    {{- end }}
    {{- end }}
    {{- with .Values.dex.sso.zitadel }}
    {{- if .enabled }}
    - secretKey: ZITADEL_CLIENT_ID
      remoteRef:
        key: {{ .clientId.key }}
        {{- with .clientId.property }}
        property: {{ . }}
        {{- end }}
    - secretKey: ZITADEL_CLIENT_SECRET
      remoteRef:
        key: {{ .clientSecret.key }}
        {{- with .clientSecret.property }}
        property: {{ . }}
        {{- end }}
    {{- end }}
    {{- end }}
    {{- with .Values.dex.sso.gitlab }}
    {{- if .enabled }}
    - secretKey: GITLAB_CLIENT_ID
      remoteRef:
        key: {{ .clientId.key }}
        {{- with .clientId.property }}
        property: {{ . }}
        {{- end }}
    - secretKey: GITLAB_CLIENT_SECRET
      remoteRef:
        key: {{ .clientSecret.key }}
        {{- with .clientSecret.property }}
        property: {{ . }}
        {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
