{{- if .Values.dex.enabled }}
{{- with .Values.dex.sso.google }}
{{- if .enabled }}
{{- if not $.Values.global.projectId }}
{{- fail "global.projectId is required when dex.sso.google.enabled" }}
{{- end }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ .serviceAccountKey.name }}
  annotations:
    cnrm.cloud.google.com/project-id: "{{ $.Values.global.projectId }}"
spec:
  displayName: "ToolHive Dex - Google Workspace groups lookup"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  name: {{ .serviceAccountKey.name }}
  annotations:
    cnrm.cloud.google.com/project-id: "{{ $.Values.global.projectId }}"
spec:
  privateKeyType: "TYPE_GOOGLE_CREDENTIALS_FILE"
  publicKeyType: "TYPE_X509_PEM_FILE"
  serviceAccountRef:
    name: {{ .serviceAccountKey.name }}
{{- end }}
{{- end }}
{{- end }}
