{{- if .Values.dex.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-vmcp-client-secret
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.kind }}
    name: {{ .Values.externalSecrets.name }}
  target:
    name: toolhive-vmcp-client-secret
    creationPolicy: {{ .Values.externalSecrets.creationPolicy }}
  data:
    - secretKey: VMCP_CLIENT_SECRET
      remoteRef:
        key: toolhive-vmcp-client-secret
{{- end }}
