{{- if .Values.dex.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-windmill-delegate-secret
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.kind }}
    name: {{ .Values.externalSecrets.name }}
  target:
    name: toolhive-windmill-delegate-secret
    creationPolicy: {{ .Values.externalSecrets.creationPolicy }}
  data:
    - secretKey: WINDMILL_DELEGATE_CLIENT_SECRET
      remoteRef:
        key: toolhive
        property: windmill-delegate-client-secret
{{- end }}
