apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.masterKey.secretName }}
spec:
  refreshInterval: "{{ .Values.externalSecrets.refreshInterval }}"
  secretStoreRef:
    kind: "{{ .Values.externalSecrets.kind }}"
    name: "{{ .Values.externalSecrets.name }}"
  target:
    name: {{ .Values.masterKey.secretName }}
    creationPolicy: "{{ .Values.externalSecrets.creationPolicy }}"
  data:
  - secretKey: masterkey
    remoteRef:
      {{- include "lamp-litellm.remoteRef" (merge (dict "name" "masterKey") .Values.masterKey.remoteRef) | nindent 6 }}
