apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.authJson.secretName }}
spec:
  refreshInterval: "{{ .Values.externalSecrets.refreshInterval }}"
  secretStoreRef:
    kind: "{{ .Values.externalSecrets.kind }}"
    name: "{{ .Values.externalSecrets.name }}"
  target:
    name: {{ .Values.authJson.secretName }}
    creationPolicy: "{{ .Values.externalSecrets.creationPolicy }}"
    template:
      data:
        auth.json: |
          {{`{{ .auth_json }}`}}
  data:
  - secretKey: auth_json
    remoteRef:
      {{- include "lamp-litellm.remoteRef" (merge (dict "name" "authJson") .Values.authJson.remoteRef) | nindent 6 }}
