{{- if .Values.deepseekApiKey }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.deepseekApiKey.secretName }}
spec:
  refreshInterval: "{{ .Values.externalSecrets.refreshInterval }}"
  secretStoreRef:
    kind: "{{ .Values.externalSecrets.kind }}"
    name: "{{ .Values.externalSecrets.name }}"
  target:
    name: {{ .Values.deepseekApiKey.secretName }}
    creationPolicy: "{{ .Values.externalSecrets.creationPolicy }}"
  data:
  - secretKey: DEEPSEEK_API_KEY
    remoteRef:
      {{- include "lamp-litellm.remoteRef" (merge (dict "name" "deepseekApiKey") .Values.deepseekApiKey.remoteRef) | nindent 6 }}
{{- end }}
