{{- if .Values.mcp.grafana.enabled }}
{{- range $item := .Values.mcp.grafana.mcps }}
{{- if not $item.instanceName }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $item.name }}-mcp-secret
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.externalSecrets.kind }}
    name: {{ $.Values.externalSecrets.name }}
  target:
    name: {{ $item.name }}-mcp-secret
    creationPolicy: {{ $.Values.externalSecrets.creationPolicy }}
  data:
    - secretKey: token
      remoteRef:
        key: {{ $item.token.key }}
        {{- with $item.token.property }}
        property: {{ . }}
        {{- end }}
{{- else }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $item.name }}-mcp-secret
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: grafana-mirror-{{ $item.instanceNamespace }}
  target:
    name: {{ $item.name }}-mcp-secret
    creationPolicy: {{ $.Values.externalSecrets.creationPolicy }}
  data:
    - secretKey: token
      remoteRef:
        key: {{ $item.name }}-mcp-secret
        property: token
{{- end }}
{{- end }}
{{- end }}
