{{- if .Values.mcp.grafana.enabled }}
{{- range $item := .Values.mcp.grafana.mcps }}
{{- if $item.instanceName }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: {{ $item.name }}
  namespace: {{ $item.instanceNamespace }}
  labels:
    dashboards: {{ $item.instanceName | quote }}
spec:
  name: {{ $item.name }}
  instanceName: {{ $item.instanceName }}
  role: {{ $item.role | default "Viewer" }}
  tokens:
    - name: {{ $item.name }}-token
      secretName: {{ $item.name }}-mcp-secret
{{- end }}
{{- end }}
{{- end }}
