apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: backstage-backend-secret-generator
  namespace: openchoreo
spec:
  length: 64
  digits: 8
  symbols: 8
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: openchoreo
spec:
  refreshInterval: 87600h
  target:
    name: backstage-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        backend-secret: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: backstage-backend-secret-generator