apiVersion: v2
name: lamp-pyroscope
version: 0.3.0

dependencies:
  - name: pyroscope
    version: 1.19.0
    repository: https://grafana.github.io/helm-charts

annotations:
  notes: "Security updates and metrics storage optimization."
