apiVersion: v2
name: lamp-pyroscope
version: 1.0.0

dependencies:
  - name: pyroscope
    version: 2.0.1
    repository: https://grafana.github.io/helm-charts

annotations:
  notes: "Security updates and metrics storage optimization."
