{{- if .Values.mcp.windmill.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: windmill-mcp-auth-header
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.kind }}
    name: {{ .Values.externalSecrets.name }}
  target:
    name: windmill-mcp-auth-header
    creationPolicy: {{ .Values.externalSecrets.creationPolicy }}
    template:
      data:
        authHeader: 'Bearer {{ "{{ .secret }}" }}'
  data:
    - secretKey: secret
      remoteRef:
        key: windmill
        property: superadmin_secret
{{- end }}
