apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.project.type }}-{{ .Values.project.environment }}-{{ .Values.project.name }}
  namespace: argocd
spec:
  generators:
    - git:
        directories:
        {{- if eq .Values.project.type "product" }}
          - path: {{ .Values.project.environment }}/{{ .Values.project.type }}/*
        {{- end }}
        {{- if eq .Values.project.type "platform" }}
          - path: {{ .Values.project.environment }}/{{ .Values.project.type }}/*
        {{- end }}
        repoURL: {{ .Values.git.repo }}
        revision: {{ .Values.git.revision }}
  {{- if .Values.sync.changeSyncPolicy }}
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  {{- end }}
  syncPolicy:
    preserveResourcesOnDeletion: {{ .Values.sync.preserveResourcesOnDeletion }}
  goTemplate: true
  template:
    metadata:
      name: "{{ .Values.project.type }}-{{ .Values.project.environment }}-{{`{{ .path.basename }}`}}"
      {{- if eq .Values.project.type "product" }}
      annotations:
        kargo.akuity.io/authorized-stage: "kargo-project-{{ .Values.project.name }}:{{`{{ .path.basename }}`}}-{{`{{ index .path.segments 1 }}`}}"
      {{- end }}
    spec:
      project: {{ .Values.project.type }}-{{ .Values.project.environment }}-{{ .Values.project.name }}
      destination:
        name: {{ .Values.project.environment }}
        {{- if eq .Values.project.type "product" }}
        namespace: product
        {{- end }}
        {{- if eq .Values.project.type "platform" }}
        namespace: "{{`{{ .path.basename }}`}}"
        {{- end }}
      source:
        helm:
          {{- if eq .Values.project.type "product" }}
          releaseName: "{{`{{ .path.basename }}`}}"
          {{- end }}
          {{- if eq .Values.project.type "platform" }}
          releaseName: "{{`{{ .path.basename }}`}}"
          {{- end }}
          passCredentials: true
          ignoreMissingValueFiles: true
          valueFiles:
            - ../values.yaml
            - values.yaml
            - .kargo.values.yaml
        path: "{{`{{ .path.path }}`}}"
        repoURL: {{ .Values.git.repo }}
        targetRevision: {{ .Values.git.revision }}
      {{- with .Values.ignoreDifferences }}
      ignoreDifferences:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      syncPolicy:
        automated:
          prune: {{ .Values.sync.prune }}
          selfHeal: {{ .Values.sync.selfHeal }}
        syncOptions:
          - CreateNamespace={{ .Values.sync.createNamespace }}
