apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ include "tplValue" (dict "value" .Values.appset.nameGenerator "context" $) | trim }}
  namespace: {{ .Values.project.namespace }}
spec:
  generators:
{{ include "tplValue" (dict "value" .Values.appset.generators "context" $) | trim | indent 4 }}
  {{- if .Values.sync.changeSyncPolicy }}
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  {{- end }}
  syncPolicy:
    preserveResourcesOnDeletion: {{ .Values.sync.preserveResourcesOnDeletion }}
  goTemplate: true
  template:
    metadata:
      name: {{ include "tplValue" (dict "value" .Values.appset.app.nameGenerator "context" $) | trim }}
      annotations:
{{ include "tplValue" (dict "value" .Values.appset.app.annotations "context" $) | trim | indent 8 }}
    spec:
      project: {{ include "tplValue" (dict "value" .Values.project.nameGenerator "context" $) | trim }}
      destination:
        name: "{{ include "tplValue" (dict "value" .Values.destination.name "context" $) | trim }}"
        namespace: "{{ include "tplValue" (dict "value" .Values.destination.namespace "context" $) | trim }}"
      source:
        helm:
          releaseName: "{{ include "tplValue" (dict "value" .Values.destination.releaseName "context" $) | trim }}"
          passCredentials: true
          ignoreMissingValueFiles: true
          {{- with .Values.git.valueFiles }}
          valueFiles:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        path: "{{ include "tplValue" (dict "value" .Values.git.path "context" $) | trim }}"
        repoURL: {{ .Values.git.repo }}
        targetRevision: {{ .Values.git.revision }}
      {{- with .Values.ignoreDifferences }}
      ignoreDifferences:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      syncPolicy:
        automated:
          prune: {{ .Values.sync.prune }}
          selfHeal: {{ .Values.sync.selfHeal }}
        syncOptions:
          - CreateNamespace={{ .Values.sync.createNamespace }}
