{{- if .Values.project.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ include "tplValue" (dict "value" .Values.project.nameGenerator "context" $) | trim }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: {{ .Values.project.description }}
  destinations:
    - name: '*'
      namespace: '*'
  sourceRepos:
    - '*'
  roles:
    - name: developer
      groups:
      {{- range .Values.project.roles.developer }}
        - {{ . }}
      {{- end }}
      policies:
        - p, proj:{{ include "tplValue" (dict "value" .Values.project.nameGenerator "context" $) | trim }}:developer, applications, *, {{ include "tplValue" (dict "value" .Values.project.nameGenerator "context" $) | trim }}/*, allow
        - p, proj:{{ include "tplValue" (dict "value" .Values.project.nameGenerator "context" $) | trim }}:developer, applicationsets, get, *, allow
        - p, proj:{{ include "tplValue" (dict "value" .Values.project.nameGenerator "context" $) | trim }}:developer, exec, create, {{ include "tplValue" (dict "value" .Values.project.nameGenerator "context" $) | trim }}/*, allow
        - p, proj:{{ include "tplValue" (dict "value" .Values.project.nameGenerator "context" $) | trim }}:developer, logs, get, {{ include "tplValue" (dict "value" .Values.project.nameGenerator "context" $) | trim }}/*, allow
{{- end }}
