apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
data:
  openclaw.json: |
    {{ .Values.config.data | toJson | nindent 4 }}
