{{- if .Values.mcp.alchemy.enabled }}
{{- range $item := .Values.mcp.alchemy.mcps }}
---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: {{ $item.name }}
spec:
  image: {{ $.Values.mcp.alchemy.image }}
  transport: stdio
  groupRef:
    name: {{ $item.groupRef | default $.Values.mcp.defaults.groupRef }}
  permissionProfile:
    type: builtin
    name: {{ $.Values.mcp.defaults.permissionProfile }}
  audit:
    enabled: true
  {{- with $item.toolConfig }}
  toolConfigRef:
    name: {{ $item.name }}-tool-config
  {{- end }}
  secrets:
    - name: {{ $item.name }}-mcp-secret
      key: api-key
      targetEnvName: ALCHEMY_API_KEY
  {{- with $item.env }}
  env:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $item.toolConfig }}
---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPToolConfig
metadata:
  name: {{ $item.name }}-tool-config
spec:
  {{- with .toolsFilter }}
  toolsFilter:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .toolsOverride }}
  toolsOverride:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
