istiod:
  profile: ambient

cni:
  cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
  cniBinDir: /var/lib/rancher/k3s/data/cni
  profile: ambient
  resources:
    requests: 
      cpu: 10m
      memory: 10Mi

ztunnel:
  resources:
    requests: 
      cpu: 10m
      memory: 10Mi
