apiVersion: v2
name: lamp-pyroscope-agent
version: 0.2.1

dependencies:
  - name: alloy
    version: 1.6.2
    repository: https://grafana.github.io/helm-charts
    condition: alloy.enabled
  - name: alloy
    alias: ebpf
    version: 1.6.2
    repository: https://grafana.github.io/helm-charts
    condition: ebpf.enabled
