apiVersion: v2
name: lamp-victoria-metrics-agent
version: 2.1.0

annotations:
  notes: "Initial version with VMAgent and several exporters (MySQL, PostgreSQL, MongoDB, Blackbox)."

dependencies:
  - name: prometheus-operator-crds
    condition: prometheus-operator-crds.enabled
    version: 27.0.0
    repository: https://prometheus-community.github.io/helm-charts

  - name: victoria-metrics-k8s-stack
    condition: victoria-metrics-k8s-stack.enabled
    version: 0.72.4
    repository: https://victoriametrics.github.io/helm-charts

  - name: prometheus-mysql-exporter
    alias: mysql-exporter
    condition: mysql-exporter.enabled
    version: 2.13.0
    repository: https://prometheus-community.github.io/helm-charts

  - name: prometheus-mongodb-exporter
    alias: mongodb-exporter
    condition: mongodb-exporter.enabled
    version: 3.18.0
    repository: https://prometheus-community.github.io/helm-charts

  - name: prometheus-postgres-exporter
    alias: postgres-exporter
    condition: postgres-exporter.enabled
    version: 7.5.1
    repository: https://prometheus-community.github.io/helm-charts

  - name: prometheus-blackbox-exporter
    alias: blackbox-exporter
    condition: blackbox-exporter.enabled
    version: 11.8.0
    repository: https://prometheus-community.github.io/helm-charts
