apiVersion: v2
dependencies:
- condition: dex.enabled
  name: dex
  repository: https://charts.dexidp.io
  version: 0.26.0
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 28.0.12
name: lamp-toolhive-vmcps
version: 0.0.4
