apiVersion: v2
name: lamp-remnawave-panel
version: 1.0.2

annotations:
  notes: "Initial version and basic configuration."

dependencies:
  - name: valkey
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: 5.4.3
    condition: valkey.enabled
  - name: postgresql
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: 18.5.15
    condition: postgresql.enabled
