apiVersion: v2
name: lamp-local-path-provisioner
version: 0.0.3

dependencies:
  - name: local-path-provisioner
    version: 0.0.36
    repository: https://charts.containeroo.ch

annotations:
  notes: "Wrapper for local-path-provisioner; configuration defaults aligned with cluster storage."
