apiVersion: v2
name: lamp-tempo-agent
version: 0.3.0

dependencies:
  - name: alloy
    version: 1.6.2
    repository: https://grafana.github.io/helm-charts
    condition: alloy.enabled
  - name: beyla
    version: 1.15.0
    repository: https://grafana.github.io/helm-charts
    condition: beyla.enabled
