{{- range $key, $val := .Values.cluster.cluster.roles }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .passwordSecret.name }}
spec:
  refreshInterval: "{{ $.Values.externalSecrets.refreshInterval }}"
  secretStoreRef:
    kind: "{{ $.Values.externalSecrets.kind }}"
    name: "{{ $.Values.externalSecrets.name }}"
  target:
    name: {{ .passwordSecret.name }}
    creationPolicy: "{{ $.Values.externalSecrets.creationPolicy }}"
    template:
      data:
        username: {{ .name }}
        password: "{{`{{ .password }}`}}"
  data:
  - secretKey: password
    remoteRef:
      key: "{{ .passwordSecret.remoteSecretKey }}"
{{- end }}
