{{- range .Values.httpRoutes }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .name }}
spec:
  {{- with .parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostnames:
  {{- range .hosts }}
    - {{ . }}
  {{- end }}
  {{- if .redirect }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
  {{- else }}
  {{- with .rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
