{{- if .Values.mcp.sheets.enabled }}
{{- range $item := .Values.mcp.sheets.mcps }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $item.name }}-mcp-secret
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.externalSecrets.kind }}
    name: {{ $.Values.externalSecrets.name }}
  target:
    name: {{ $item.name }}-mcp-secret
    creationPolicy: {{ $.Values.externalSecrets.creationPolicy }}
    template:
      engineVersion: v2
      data:
        credentials-config: '{{ "{{" }} .serviceAccountJson | b64enc {{ "}}" }}'
  data:
    - secretKey: serviceAccountJson
      remoteRef:
        key: {{ $item.credentials.key }}
        {{- with $item.credentials.property }}
        property: {{ . }}
        {{- end }}
{{- end }}
{{- end }}
