tempo:
  enabled: true
  reportingEnabled: false
  global:
    storageClass: local-path
  distributor:
    service:
      annotations:
        tailscale.com/expose: 'true'
  compactor:
    config:
      compaction:
        block_retention: 336h # 14 days
  ingester:
    persistence:
      enabled: true
    config:
      complete_block_timeout: 5m
      max_block_duration: 10m
  traces:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
    jaeger:
      grpc:
        enabled: true
  tempo:
    structuredConfig:
      query_frontend:
        search:
          max_duration: 336h0m0s
  gateway:
    enabled: false

  metricsGenerator:
    enabled: true
    config:
      storage:
        remote_write:
          - url: http://vminsert-victoria-metrics.victoria-metrics:8480/insert/0/prometheus/api/v1/write #

  minio:
    enabled: false

  metaMonitoring:
    grafanaAgent:
      enabled: false
      installOperator: false

vulture:
  enabled: true
  podMonitor:
    enabled: true
  tempoAddress:
    push: grpc://tempo-distributor
    query: http://tempo-query-frontend:3200
