{{- if .Values.mcp.kubernetes.enabled }}
{{- range $item := .Values.mcp.kubernetes.mcps }}
{{- if $item.kubeconfig }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $item.name }}-mcp-secret
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.externalSecrets.kind }}
    name: {{ $.Values.externalSecrets.name }}
  target:
    name: {{ $item.name }}-mcp-secret
    creationPolicy: {{ $.Values.externalSecrets.creationPolicy }}
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: {{ $item.kubeconfig.key }}
        {{- with $item.kubeconfig.property }}
        property: {{ . }}
        {{- end }}
{{- end }}
{{- end }}
{{- end }}
