{{- range .Values.clusterStores }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
stringData:
  privateKey: |
    {{- .privateKey | b64dec | nindent 4 }}
  fingerprint: {{ .fingerprint | quote }}
{{- end }}
