apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-config
spec:
  refreshInterval: "{{ $.Values.externalSecrets.refreshInterval }}"
  secretStoreRef:
    kind: "{{ $.Values.externalSecrets.kind }}"
    name: "{{ $.Values.externalSecrets.name }}"
  target:
    name: renovate-config
    creationPolicy: "{{ .Values.externalSecrets.creationPolicy }}"
    template:
      data:
        config.json: |
          {
            "gitAuthor": "{{ .Values.config.gitAuthor }}",
            "platform": "{{ .Values.config.platform }}",
            "endpoint":  "{{ .Values.config.endpoint }}",
            "token": "{{`{{ .token }}`}}",
            "autodiscover": {{ .Values.config.autodiscover }},
            "printConfig": {{ .Values.config.printConfig }},
            "repositories": {{ toJson .Values.config.repositories }},
            "allowedCommands": {{ toJson .Values.config.allowedCommands }}
          }
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.config.token.key }}
        {{- with .Values.config.token.property }}
        property: {{ . }}
        {{- end }}
