{{- if index .Values "mysql-exporter" "enabled" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-exporter-auth
spec:
  refreshInterval: "{{ .Values.externalSecrets.refreshInterval }}"
  secretStoreRef:
    kind: "{{ .Values.externalSecrets.kind }}"
    name: "{{ .Values.externalSecrets.name }}"
  target:
    name: mysql-exporter-auth
    creationPolicy: "{{ .Values.externalSecrets.creationPolicy }}"
    template:
      data:
        config: |
          [client]
          host={{ include "auth.host" (index .Values "mysql-exporter") }}
          port={{ include "auth.port" (index .Values "mysql-exporter") }}
          user={{ include "auth.user" (index .Values "mysql-exporter") }}
          password={{ include "auth.pass" (index .Values "mysql-exporter") }}
  data:
    {{- include "auth.remoteRefs" (index .Values "mysql-exporter") | nindent 4 }}
{{- end }}
