{{ if .Values.rollout.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cloudflare-tunnel-remote.fullname" . }}-rollout
spec:
  schedule: "{{ .Values.rollout.cron }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "cloudflare-tunnel-remote.fullname" . }}-rollout
          nodeSelector:
            {{- toYaml .Values.nodeSelector | nindent 12 }}
          containers:
          - name: kubectl
            image: bitnamilegacy/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              kubectl rollout restart deployment {{ include "cloudflare-tunnel-remote.fullname" . }} -n {{ .Release.Namespace }}
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudflare-tunnel-remote.fullname" . }}-rollout
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cloudflare-tunnel-remote.fullname" . }}-rollout
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cloudflare-tunnel-remote.fullname" . }}-rollout
subjects:
- kind: ServiceAccount
  name: {{ include "cloudflare-tunnel-remote.fullname" . }}-rollout
roleRef:
  kind: Role
  name: {{ include "cloudflare-tunnel-remote.fullname" . }}-rollout
  apiGroup: rbac.authorization.k8s.io
{{- end }}
