apiVersion: v2
name: lamp-trivy-operator
version: 0.2.0

dependencies:
  - name: trivy-operator
    version: 0.36.0
    repository: https://aquasecurity.github.io/helm-charts/

annotations:
  notes: "Using Trivy Operator v0.29.0, critical security fixes."
