config:
  autodiscover: false
  printConfig: false
  repositories: ["from-the-lamp/infra/helm-charts"]
  platform: gitlab
  endpoint: https://gitlab.com/api/v4
  token:
    key: gitlab
    property: token_legacy
  gitAuthor: "Renovate Bot <renovate@from-the-lamp.work>"
  allowedCommands: []

renovate:
  renovate:
    existingConfigFile: /etc/renovate/config.json
  extraVolumes:
    - name: renovate-config
      secret:
        secretName: renovate-config
  extraVolumeMounts:
    - name: renovate-config
      mountPath: /etc/renovate
      readOnly: true

externalSecrets:
  kind: ClusterSecretStore
  name: vault
  refreshInterval: 1h
  creationPolicy: Orphan
