apiVersion: v2
name: lamp-external-secrets
version: 1.2.0

dependencies:
  - name: external-secrets
    version: 2.4.0
    repository: https://charts.external-secrets.io

annotations:
  notes: "Change image registry to ghcr.io, fixed Oracle connection leaks."
