{{- if .Values.datasources.tempo.enabled }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: tempo
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: {{ .Values.datasources.tempo.url}}
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        customQuery: true
        query: '{service_name=~".+"} |= "trace_id=${__span.traceId}"'
{{- end }}
