image:
  name: tailscale/tailscale
  tag: stable

externalSecrets:
  kind: ClusterSecretStore
  name: oracle
  refreshInterval: 1h
  creationPolicy: Orphan

remoteSecretKeys:
  tailscale: tailscale

connectors:
  - name: k3s-infra-subnet-router
    hostname: k3s-infra-subnet-router
    advertiseRoutes:
      - 10.43.0.0/16

hostNodes:
  - name: exit
    hostname: k3s-infra-exit-direct
    exitNode: true
    tags:
      - tag:exit
    nodeSelector:
      kubernetes.io/hostname: infra-worker-03
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
    sysctls:
      net.core.rmem_max: "7500000"
      net.core.wmem_max: "7500000"
    # stateSecret: tailscale-exit-state
    # tolerations: []
    # advertiseRoutes:
    #   - 10.0.1.0/24
