project:
  enabled: true
  name: example
  nameGenerator: "{{ .Values.project.type }}-{{ .Values.project.environment }}-{{ .Values.project.name }}"
  namespace: argocd
  type: product
  description: ""
  environment: dev
  roles:
    developer: []

git:
  repo: https://git.example
  revision: HEAD
  path: "{{`{{ .path.path }}`}}"
  valueFiles:
    - ../values.yaml
    - values.yaml
    - .kargo.values.yaml

appset:
  name: example
  nameGenerator: "{{ .Values.project.type }}-{{ .Values.project.environment }}-{{ .Values.project.name }}"
  generators:
    - git:
        files:
          - path: "{{ .Values.project.environment }}/{{ .Values.project.type }}/*/appConfig.yaml"
        repoURL: "{{ .Values.git.repo }}"
        revision: "{{ .Values.git.revision }}"
  app:
    nameGenerator: "{{ .Values.project.type }}-{{ .Values.project.environment }}-{{`{{ .path.basename }}`}}"
    annotations:
      kargo.akuity.io/authorized-stage: "kargo-project-{{`{{ .path.basename }}`}}:{{ .Values.project.environment }}-{{`{{ .path.basename }}`}}"
      
destination:
  name: "{{ .Values.project.environment }}"
  namespace: "{{`{{ .path.basename }}`}}"
  releaseName: "{{`{{ .path.basename }}`}}"

sync:
  prune: true
  selfHeal: true
  createNamespace: true
  changeSyncPolicy: true
  preserveResourcesOnDeletion: true

ignoreDifferences:
  - group: apps
    jqPathExpressions:
      - .spec.volumeClaimTemplates[].apiVersion
      - .spec.volumeClaimTemplates[].kind
    jsonPointers:
      - /spec/replicas
    kind: StatefulSet
  - group: apps
    jsonPointers:
      - /spec/replicas
    kind: Deployment
  - group: admissionregistration.k8s.io
    jsonPointers:
      - /webhooks/0/failurePolicy
    kind: ValidatingWebhookConfiguration
    name: istio-validator-istio-system
  - group: admissionregistration.k8s.io
    jsonPointers:
      - /webhooks/0/failurePolicy
    kind: ValidatingWebhookConfiguration
    name: istiod-default-validator
  - group: ""
    kind: Service
    jsonPointers:
      - /spec/externalName
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
      - /spec/preserveUnknownFields
  - group: postgresql.cnpg.io
    kind: Cluster
    jqPathExpressions:
      - .spec.managed.roles[].passwordSecret.remoteSecretKey
      - .spec.managed.roles[].passwordSecret.remoteSecretProperty