project:
  enabled: true
  type: product
  name: example
  description: ""
  environment: #dev
  roles:
    developer: []

git:
  repo: https://git.example
  revision: HEAD

sync:
  prune: true
  selfHeal: true
  createNamespace: true
  changeSyncPolicy: true
  preserveResourcesOnDeletion: true

ignoreDifferences:
  - group: apps
    jqPathExpressions:
      - .spec.volumeClaimTemplates[].apiVersion
      - .spec.volumeClaimTemplates[].kind
    jsonPointers:
      - /spec/replicas
    kind: StatefulSet
  - group: apps
    jsonPointers:
      - /spec/replicas
    kind: Deployment
  - group: admissionregistration.k8s.io
    jsonPointers:
      - /webhooks/0/failurePolicy
    kind: ValidatingWebhookConfiguration
    name: istio-validator-istio-system
  - group: admissionregistration.k8s.io
    jsonPointers:
      - /webhooks/0/failurePolicy
    kind: ValidatingWebhookConfiguration
    name: istiod-default-validator
  - group: ""
    kind: Service
    jsonPointers:
      - /spec/externalName
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
      - /spec/preserveUnknownFields