{{- if .Values.mcp.thegraph.enabled }}
{{- range $item := .Values.mcp.thegraph.mcps }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $item.name }}-mcp-secret
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.externalSecrets.kind }}
    name: {{ $.Values.externalSecrets.name }}
  target:
    name: {{ $item.name }}-mcp-secret
    creationPolicy: {{ $.Values.externalSecrets.creationPolicy }}
  data:
    - secretKey: api-key
      remoteRef:
        key: {{ $item.token.key }}
        {{- with $item.token.property }}
        property: {{ . }}
        {{- end }}
{{- end }}
{{- end }}
