{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: immich-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: immich-backup
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: immich-backup
subjects:
  - kind: ServiceAccount
    name: immich-backup
roleRef:
  kind: Role
  name: immich-backup
  apiGroup: rbac.authorization.k8s.io
{{- end }}
