{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: immich-restore
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: immich-restore
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: immich-restore
subjects:
  - kind: ServiceAccount
    name: immich-restore
roleRef:
  kind: Role
  name: immich-restore
  apiGroup: rbac.authorization.k8s.io
{{- end }}
