cluster:
  mode: standalone
  type: postgresql
  fullnameOverride: postgres
  cluster:
    instances: 1
    logLevel: info
    primaryUpdateStrategy: unsupervised
    postgresql:
      parameters:
        max_connections: "1000"
        shared_buffers: 256MB
        pg_stat_statements.max: '10000'
        pg_stat_statements.track: all
        auto_explain.log_min_duration: '10s'
      pg_hba: []
        # - "host all all 10.244.0.0/16 md5"
    storage:
      size: 10Gi
      storageClass: local-path
    walStorage:
      size: 1Gi
      storageClass: local-path
    monitoring:
      enabled: true
      podMonitor:
        enabled: true
      prometheusRule:
        excludeRules:
          - CNPGClusterHAWarning
          - CNPGClusterHACritical
    enableSuperuserAccess: true
    superuserSecret: postgres-superuser
    superuser:
      username: postgres
      password:
        key: postgres-superuser-password
        property: pass

    databases: []
      # - name: example
      #   owner: example
      #   publication:
      #     enabled: true
      #     allTables: true

    roles: []
      # - name: example
      #   ensure: present
      #   login: true
      #   superuser: false
      #   connectionLimit: -1
      #   inherit: true
      #   passwordSecret:
      #     name: postgres-example-password
      #     remoteSecret:
      #       key: postgres-example-password
      #       property: password

  poolers:
    - name: rw
      type: rw
      poolMode: transaction
      instances: 1
      parameters:
        max_client_conn: "1000"
        default_pool_size: "25"
      monitoring:
        enabled: true
        podMonitor:
          enabled: true
      template: {}

  backups:
    enabled: false
    method: plugin
    pluginConfiguration:
      name: barman-cloud.cloudnative-pg.io
    provider: s3
    endpointURL: ""
    s3:
      region: ""
      bucket: ""
      path: "/"
    secret:
      create: false
      name: ""
    retentionPolicy: 30d
    scheduledBackups:
      - name: daily-backup
        schedule: "0 0 0 * * *"
        backupOwnerReference: self
        method: plugin
        pluginConfiguration:
          name: barman-cloud.cloudnative-pg.io

backupCredentials:
  remoteSecretKey: s3
  accessKeyProperty: backblaze.from-the-lamp.id
  secretKeyProperty: backblaze.from-the-lamp.secret

externalSecrets:
  kind: ClusterSecretStore
  name: "" #
  refreshInterval: 1h
  creationPolicy: Orphan
