global:
  projectId: ""
  
defaultClusterName: ""

gcp:
  workloadIdentity:
    enabled: false
    serviceAccountName: argocd-repo-server

sso:
  enabled: false
  secretName: argocd-sso
  oauthClientID:
    key: argocd
    property: oauth-client-id
  oauthClientSecret:
    key: argocd
    property: oauth-client-secret
  googleServiceAccountKey:
    enabled: false
    name: argocd-sso-gsa

externalClusters: []

repositories: []

githubApps: []

externalSecrets:
  kind: ClusterSecretStore
  name: ""
  refreshInterval: 1h
  creationPolicy: Orphan

argo-cd:
  configs:
    params:
      server.insecure: "true"
    rbac:
      policy.default: deny
      scopes: "[email, groups]"
    cm:
      admin.enabled: false
      exec.enabled: true

  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  server:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  repoServer:
    serviceAccount:
      name: argocd-repo-server
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  applicationSet:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  notifications:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  redis:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    exporter:
      enabled: true
