kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: oci-cloud-controller-manager
stringData:
  cloud-provider.yaml: |
    auth:
      compartment: {{ .Values.config.compartment }}
      vcn: {{ .Values.config.vcn }}
      useInstancePrincipals: true
    loadBalancer:
      securityListManagementMode: All
      subnet1: {{ .Values.config.subnet1 }}
