image:
  name: tailscale/tailscale
  tag: stable

externalSecrets:
  kind: ClusterSecretStore
  name: oracle
  refreshInterval: 1h
  creationPolicy: Orphan

remoteSecretKeys:
  clientSecret: tailscale-client-secret

proxyClasses:
  - name: exit-node
    pod:
      tailscaleContainer:
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
      # nodeSelector:
      #   kubernetes.io/hostname: infra-worker-03
      # securityContext:
      #   sysctls:
      #     - name: net.core.rmem_max
      #       value: "7500000"

connectors:
  - name: exit-node
    hostname: k3s-infra-exit-node
    exitNode: true
    proxyClass: exit-node
    tags:
      - tag:exit
    # replicas: 1
    # hostnamePrefix: k3s-infra-exit-node
    # advertiseRoutes:
    #   - 10.0.1.0/24

hostNodes:
  - name: exit
    hostname: k3s-infra-exit-direct
    exitNode: true
    tags:
      - tag:exit
    nodeSelector:
      kubernetes.io/hostname: infra-worker-03
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
    sysctls:
      net.core.rmem_max: "7500000"
      net.core.wmem_max: "7500000"
    # stateSecret: tailscale-exit-state
    # tolerations: []
    # advertiseRoutes:
    #   - 10.0.1.0/24
