apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.library.storageClass }}
  resources:
    requests:
      storage: {{ .Values.library.size }}
