image:
  name: remnawave/node
  tag: 2.1.6
  pullPolicy: IfNotPresent
  pullSecrets: []

deployment:
  replicas: 1
  annotations: {}

existingSecret: ""
env:
  SSL_CERT: "eyJub2RlQ2VydFBlbSI6Ii0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJQmZqQ0NBU09nQXdJQkFnSUhBWFZ5Z1dkVll6QUtCZ2dxaGtqT1BRUURBakFvTVNZd0pBWURWUVFERXgxblxuYWtFeVZDMHdha3B5TkhOMGMzaHdSMG8zV25RMWRsTkJUVFZsVnpBZUZ3MHlOVEE1TURjeU1UUTNOVFZhRncweVxuT0RBNU1EY3lNVFEzTlRWYU1DZ3hKakFrQmdOVkJBTVRIVUZxWXpjNVdEQjFSVXgxYzNrNGNGazJWVnBuWVdKQlxuWlhGMVJYTjVNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVIUzF3MVNHUW1ValphemZhWmp6N1xua2xIQ2pPaG9hTVJBLyttS0VPS0dRZEt5c3MycnNLYWdPeDBBTXZrbnl3UEducFkvdkd5ZFlTVE1CTGhZTjh6RVxuZTZNNE1EWXdEQVlEVlIwVEFRSC9CQUl3QURBT0JnTlZIUThCQWY4RUJBTUNCYUF3RmdZRFZSMGxBUUgvQkF3d1xuQ2dZSUt3WUJCUVVIQXdFd0NnWUlLb1pJemowRUF3SURTUUF3UmdJaEFPN3Q0bWk4YStsR0ZHVjhvZmxXbG9kK1xuR1RiQU1tb0pOZFBqbnBHZGRjd2dBaUVBbkpTeFhSUlRxeERGUEZ0ZS81RUJqSEdrRlBFVFZzUWxLU0t6NnB0d1xuaElnPVxuLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLSIsIm5vZGVLZXlQZW0iOiItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ3BWUG9keFZGa2lyb3hZQjhcbk9XbHNFVUlVR0pnVHV3ekZKUVJyNFRJTDZJZWhSQU5DQUFRZExYRFZJWkNaU05sck45cG1QUHVTVWNLTTZHaG9cbnhFRC82WW9RNG9aQjByS3l6YXV3cHFBN0hRQXkrU2ZMQThhZWxqKzhiSjFoSk13RXVGZzN6TVI3XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tIiwiY2FDZXJ0UGVtIjoiLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tXG5NSUlCWWpDQ0FRaWdBd0lCQWdJQkFUQUtCZ2dxaGtqT1BRUURBakFvTVNZd0pBWURWUVFERXgxbmFrRXlWQzB3XG5ha3B5TkhOMGMzaHdSMG8zV25RMWRsTkJUVFZsVnpBZUZ3MHlOVEE1TURjeU1UUTJNekJhRncwek5UQTVNRGN5XG5NVFEyTXpCYU1DZ3hKakFrQmdOVkJBTVRIV2RxUVRKVUxUQnFTbkkwYzNSemVIQkhTamRhZERWMlUwRk5OV1ZYXG5NRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVDS1Vja0k0YVBJNmU4SCtpU3k4QWwyLzlmSHZpXG5SUjBmYm9KT3ByQjZRMEsySlU4VzlYdG9zSWFXcnZOVWtKK1Nia0JHd29XMTYxUEFrQlJhVmo1bWU2TWpNQ0V3XG5Ed1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0NnWUlLb1pJemowRUF3SURTQUF3XG5SUUlnYUczSEJSWk1mZWxuaEF3S1l0UHh0UTRKNFhaanRPdlZnaHRiSWpDTy8zTUNJUURZd0VRd3dZWm9hdFpUXG5CTXl2MjdlL1FkcVVrem9BUVJSdCt6MnZJNThUMFE9PVxuLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLSIsImp3dFB1YmxpY0tleSI6Ii0tLS0tQkVHSU4gUFVCTElDIEtFWS0tLS0tXG5NSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdwOFJjaFhRRjFDM0xudkxBeklNXG51N1ExOFpKUm5oaFZaRlhKRkxCdm1jOG5vQ3lNSkt5ZnA4OGpaUWpveXhSYm1HTlAxT2xKaG4yV0R3V1JJbTV2XG5OK0tDVDNFNkRkdlZ1aHZGVFBBeEt2OFc3WDJkMzY5a1lXMXBocWpvdk91dXViUWVOanpNbkxHMGFHMkVDS2kyXG5GdXJOOU9YY2JQTjVlV0tHSFV4aGt6VC9CZG4vOEE2N1hPZGd4Q2NtUVhGVXhvUW5kbFlENDVaNU9rUGhpK2VuXG52TW8rZVNLWCtPTzgwNHJUemh0dU9sYlc3TmIwQkJjdWxpNnF0MkNUK0krSTVkSERDYmxJYVVYTExoaC93OURyXG5lMkFwOFZvbFVhYW9CTWl6Wk0xR2l1b0JvMjI5UC9YMnNDemFCU1VMeFlaWTVuRVlaeWN2azVlLy9iZVdlcC95XG40UUlEQVFBQlxuLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tXG4ifQ=="

service:
  type: LoadBalancer
  externalTrafficPolicy: Local
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
    oci-network-load-balancer.oraclecloud.com/security-list-management-mode: "All"
  ports:
    - name: node
      port: 2222
      targetPort: 2222
      protocol: TCP
    - name: xray
      port: 1234
      targetPort: 1234
      protocol: TCP
