apiVersion: v2
name: lamp-coredns
version: 0.2.1

dependencies:
  - name: coredns
    alias: private-resolver
    version: 1.45.2
    repository: https://coredns.github.io/helm

annotations:
  notes: "CoreDNS image update to v1.13.1."
