httpRoutes:
  - name: book
    parentRefs:
    - name: istio-gateway-internal
      namespace: istio-system
    hosts:
      - argocd.internal.from-the-lamp.work
    rules:
      - backendRefs:
        - name: argocd-argocd-server
          port: 80
