apiVersion: v2
name: lamp-renovate
version: 1.1.0

dependencies:
  - name: renovate
    version: 46.67.0
    repository: oci://ghcr.io/renovatebot/charts

annotations:
  notes: "Dependency update and Renovate stability improvements."