apiVersion: v2
name: lamp-renovate
version: 1.2.0

dependencies:
  - name: renovate
    version: 46.68.1
    repository: oci://ghcr.io/renovatebot/charts

annotations:
  notes: "Dependency update and Renovate stability improvements."