{{- if .Values.dex.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-authserver-secrets
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.kind }}
    name: {{ .Values.externalSecrets.name }}
  target:
    name: toolhive-authserver-secrets
    creationPolicy: {{ .Values.externalSecrets.creationPolicy }}
  data:
    - secretKey: hmac
      remoteRef:
        key: toolhive-authserver-hmac
    - secretKey: signing
      remoteRef:
        key: toolhive-authserver-signing
{{- end }}
