{{- if .Values.redis.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.redis.auth.existingSecret }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.externalSecrets.kind }}
    name: {{ $.Values.externalSecrets.name }}
  target:
    name: {{ .Values.redis.auth.existingSecret }}
    creationPolicy: {{ $.Values.externalSecrets.creationPolicy }}
  data:
    - secretKey: {{ .Values.redis.auth.existingSecretPasswordKey }}
      remoteRef:
        key: {{ .Values.redis.passwordSecret.key }}
        {{- with .Values.redis.passwordSecret.property }}
        property: {{ . }}
        {{- end }}
{{- end }}
