remoteSecretKeys:
  token: gitlab-runner-token

gitlab-runner:
  gitlabUrl: https://gitlab.com
  rbac:
    create: true
  serviceAccount:
    create: true
    name: gitlab-runner
  runners:
    serviceAccountName: gitlab-runner
    secret: gitlab-runner
    config: |
      [[runners]]
        request_concurrency = 2
        [runners.feature_flags]
          FF_USE_ADAPTIVE_REQUEST_CONCURRENCY = true
        [runners.kubernetes]
          namespace = "{{ default .Release.Namespace .Values.runners.jobNamespace }}"
          image = "ubuntu:latest"
          helper_image = "gitlab/gitlab-runner-helper:arm64-latest"
          privileged = true
     
externalSecrets:
  kind: ClusterSecretStore
  name: oracle
  refreshInterval: 1h
  creationPolicy: Orphan
